# Generated by Django 5.2.9 on 2025-12-10 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True)),
                ('telefon', models.CharField(max_length=20)),
                ('resim_linki', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Yemek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restoran')),
            ],
        ),
    ]
