# Generated by Django 5.2.9 on 2025-12-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restoran',
            options={'verbose_name': 'Restoran', 'verbose_name_plural': 'Restoranlar'},
        ),
        migrations.AlterModelOptions(
            name='yemek',
            options={'verbose_name': 'Yemek', 'verbose_name_plural': 'Yemek Menüsü'},
        ),
        migrations.AddField(
            model_name='yemek',
            name='icerik',
            field=models.TextField(blank=True, help_text='Örn: Soğan, turşu, özel sos...', verbose_name='İçindekiler / Not'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Örn: En lezzetli hamburgerlerin adresi.', verbose_name='Kısa Açıklama'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Restoran Adı'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='resim_linki',
            field=models.CharField(blank=True, help_text="Google'dan kopyaladığınız resim adresini buraya yapıştırın.", max_length=500, verbose_name='Kapak Fotoğrafı (Link)'),
        ),
        migrations.AlterField(
            model_name='restoran',
            name='telefon',
            field=models.CharField(help_text='Müşterilerin arayacağı numara (Örn: 0212...)', max_length=20, verbose_name='Sipariş Hattı'),
        ),
        migrations.AlterField(
            model_name='yemek',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Fiyat (₺)'),
        ),
        migrations.AlterField(
            model_name='yemek',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Yemek Adı'),
        ),
        migrations.AlterField(
            model_name='yemek',
            name='restoran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restoran', verbose_name='Hangi Restoran?'),
        ),
    ]
