# Generated by Django 5.2.9 on 2025-12-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_restoran_options_alter_yemek_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yemek',
            name='resim',
            field=models.CharField(blank=True, help_text='Yemeğin fotoğraf linkini buraya yapıştırın.', max_length=500, verbose_name='Yemek Fotoğrafı (Link)'),
        ),
    ]
