# Generated by Django 5.2.9 on 2025-12-10 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_yemek_resim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sikayet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(blank=True, default='Anonim', max_length=100, verbose_name='Müşteri Adı')),
                ('konu', models.CharField(choices=[('teslimat', 'Teslimat Çok Geç Kaldı'), ('lezzet', 'Yemek Soğuk/Lezzetsiz'), ('davranis', 'Kurye Davranışı'), ('diger', 'Diğer Sebepler')], max_length=100, verbose_name='Şikayet Konusu')),
                ('mesaj', models.TextField(verbose_name='Şikayet Detayı')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restoran', verbose_name='Şikayet Edilen Restoran')),
            ],
            options={
                'verbose_name': 'Şikayet',
                'verbose_name_plural': 'Gelen Şikayetler',
                'ordering': ['-tarih'],
            },
        ),
    ]
