# Generated by Django 5.2.9 on 2025-12-10 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sikayet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(help_text='Örn: Ekstra Peynir, Acı Sos', max_length=100, verbose_name='Seçenek Adı')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ekstra Fiyat')),
                ('yemek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secenekler', to='core.yemek')),
            ],
        ),
    ]
