# Generated by Django 5.2.9 on 2025-12-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_secenek'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoranBasvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restoran_adi', models.CharField(max_length=100)),
                ('yetkili_adi', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('sehir', models.CharField(max_length=50)),
                ('kvkk_onayi', models.BooleanField(default=False)),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Restoran Başvurusu',
                'verbose_name_plural': 'Restoran Başvuruları',
            },
        ),
    ]
