# Generated by Django 6.0 on 2025-12-12 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sepet_sepeturun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('adres', models.TextField(verbose_name='Teslimat Adresi')),
                ('adres_tarifi', models.TextField(blank=True, verbose_name='Adres Tarifi')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Toplam Tutar')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('durum', models.CharField(choices=[('hazirlaniyor', 'Hazırlanıyor'), ('yolda', 'Yolda'), ('teslim_edildi', 'Teslim Edildi'), ('iptal', 'İptal Edildi')], default='hazirlaniyor', max_length=20, verbose_name='Sipariş Durumu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SiparisUrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(verbose_name='Adet')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Birim Fiyat (TL)')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.siparis', verbose_name='Sipariş')),
                ('yemek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.yemek', verbose_name='Yemek')),
            ],
            options={
                'verbose_name': 'Sipariş Ürünü',
                'verbose_name_plural': 'Sipariş Ürünleri',
            },
        ),
    ]
