# Generated by Django 6.0 on 2025-12-12 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_siparis_siparisurun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.PositiveIntegerField(default=5, verbose_name='Puan (1-5)')),
                ('yorum', models.TextField(verbose_name='Yorumunuz')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Yorum Tarihi')),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='core.restoran', verbose_name='Restoran')),
                ('siparis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.siparis', verbose_name='Sipariş')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['-tarih'],
            },
        ),
    ]
