# Generated by Django 5.2.9 on 2025-12-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_yorum'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='Oturum ID')),
                ('customer_name', models.CharField(blank=True, default='Ziyaretçi', max_length=100, verbose_name='Müşteri Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Sohbet Oturumu',
                'verbose_name_plural': 'Sohbet Oturumları',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Kullanıcı'), ('admin', 'Admin')], max_length=10, verbose_name='Gönderen')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatsession', verbose_name='Oturum')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['timestamp'],
            },
        ),
    ]
