# Generated by Django 5.2.9 on 2025-12-12 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_chatsession_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Kupon Kodu')),
                ('indirim_yuzdesi', models.PositiveIntegerField(help_text='Örn: 10 yazarsanız %10 indirim yapar.', verbose_name='İndirim Yüzdesi (%)')),
                ('min_sepet_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Min. Sepet Tutarı')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Kupon',
                'verbose_name_plural': 'Kuponlar',
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restoran', verbose_name='Restoran')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoriler',
                'unique_together': {('user', 'restoran')},
            },
        ),
    ]
