# Generated by Django 5.2.9 on 2025-12-12 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_kupon_favori'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kart_adi', models.CharField(help_text='Örn: İş Bankası Maaş', max_length=50, verbose_name='Kartın Adı')),
                ('kart_sahibi', models.CharField(max_length=100, verbose_name='Kart Sahibi')),
                ('kart_numarasi', models.CharField(max_length=20, verbose_name='Kart Numarası (Maskelenmiş)')),
                ('son_kullanma_ay', models.CharField(max_length=2, verbose_name='Ay')),
                ('son_kullanma_yil', models.CharField(max_length=4, verbose_name='Yıl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kayıtlı Kart',
                'verbose_name_plural': 'Kayıtlı Kartlar',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('adres', models.TextField(blank=True, verbose_name='Varsayılan Adres')),
                ('dogum_tarihi', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
    ]
